### ISSUE TITLE
Which versions of Node.js should nodejs-bin make available?

### ISSUE THREAD

**Issue by samwillis** [samwillis/nodejs-pypi#1]
I'm looking for thoughts on which versions of Node.js you would like to see made available via PyPI by nodejs-bin.

See:

- https://nodejs.org/dist/
- https://nodejs.org/en/about/releases/

I'm personally inclined to just do Current+LST, so currently v14,16,18.

There other aspect of it is how many point realises to repackage and make available, again I'm inclined not to do anything other than the latest point release for supported versions. But would be interested in hearing peoples thoughts!

Important to note that nodejs-bin uses valuable PyPI resources (it doesn't download from [http://nodejs.org](https://t.co/Q4cRIJLlVm)) to store these packages. There have been over 700 releases of Node.js, and at least 6 platforms for each. It would be something like 150GB of storage. I'm not even sure PyPI would even let us store that much.

**Comment by luzfcb** [comment]
I think storing is still the least of the problems, I think the bandwidth expense would be very, very large if this project gains traction.
I would like to know what the few PyPI maintainers think about storing and maintaining large binaries on PyPI
