### ISSUE TITLE
Should nodejs-bin be split in two, separating "node", "npm" commands on the path into a second optional package?

### ISSUE THREAD

**Issue by samwillis** [samwillis/nodejs-pypi#2]
Currently nodejs-bin provides "node", "npm" etc. commands as Python package "entry points" replicating the expected commands available on users PATH. However if a Python package adds nodejs-bin as a **default** dependency it would potentially supersede a users Node version that they have installed via a different method.

One option is to split the package into two, "nodejs-bin" which excludes the "node", "npm" etc. commands and requires you ether call node with the python API or with the `python -m nodejs` method. And a "nodejs-cmd" package that adds the "node", "npm" commands, it would require "nodejs-bin" itself.

The alternatively is we keep it as it is and strongly push users to only ever add nodejs-bin as an **optional** dependency. However, I think there are potential use cases where having it available "pathless" would be useful.

I would be interested in peoples thoughts on this as well as how best to implement it, as different versions of Node.js have different commands available (very old versions didn't package `npm`, and there is a newer `corepack` command) - it would however the less of an issue if we don't repack older versions of Node.

**Comment by samwillis** [comment]
Just an update on my thoughts here, I'm 99% sure I'm going to split the `node`, `npm` and `npx` command out as a separate optional package, much safer and more flexible. So to get them the user would:

```shell
pip install node-bin[cmd]
```

**Comment by timonweb** [comment]
I like the idea of `pip install nodejs-bin[cmd]`!
