### ISSUE TITLE
Add a second project URL on PyPI that links to this repository

### ISSUE THREAD

**Issue by jack1142** [samwillis/nodejs-pypi#4]
I don't know what would be the best name for the link but it would help with discoverability if there was a link to this repository in Project links sidebar in addition to the one in the project description, see the cmake package as an example:
https://pypi.org/project/cmake/

Especially true when one ends up having some issues with the package, it's important that you can find the place where you can report the issues about this project rather than just node.js :)

**Comment by samwillis** [comment]
Thanks @jack1142, good suggestion. I have just released and new version doing just that.
