### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by RobertCraigie** [samwillis/nodejs-pypi#6]
Would be really nice for the Python API if this project provided type hints along with a `py.typed` marker file :)

In terms of the actual implementation, the easiest solution, due to the multitude of overloads on the subprocess functions, would probably be to alias them, e.g.

```py
import subprocess
from typing import TYPE_CHECKING

if TYPE_CHECKING:
  run = subprocess.run
  ...
else:
  def run(args, **kwargs):
    return subprocess.run([path, *args], **kwargs)
  ...
```

For context, I'm planning on supporting this package in https://github.com/RobertCraigie/prisma-client-py which is very strictly typed which means Pyright complains that this package is missing type hints or if any method / variable I access does not have a known type.

```py
from nodejs import node  # error: Stub file not found for "nodejs"
```

**Comment by samwillis** [comment]
Ah, awesome! I had gone looking for how best to add type annotations to this and wasn't sure the bast way. It looks like that would be compatible all the way back to 3.5 too, so that good.

I shall make those changes, Thanks!

**Comment by samwillis** [comment]
Hi @RobertCraigie,

I have just released a new version that adds these type aliases and the import pattern from your other issue. If you could let me know how you get on with Pyright, that would be awesome!
